name: Execute Discord Webhooks

on:
    push:
    watch:
        types: [started]

jobs:
    discord-webhooks:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Execute Discord Webhooks
              uses: FancyStudioTeam/GitHub-Actions@main
              with:
                  webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
                  webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
